### ISSUE TITLE
CentOS debug

### ISSUE THREAD

**Issue by wmbutler** [Gottox/node-pdfutils#10]
```
[bbutler@PDF001 adventhp]$ sudo npm install pdfutils
npm WARN package.json adventhp@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/pdfutils
npm http 304 https://registry.npmjs.org/pdfutils

> pdfutils@0.3.2 install /home/adventhp/node_modules/pdfutils
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.28"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/adventhp/node_modules/pdfutils/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
make: Entering directory `/home/adventhp/node_modules/pdfutils/build'
  CXX(target) Release/obj.target/pdfutils/src/document.o
  CXX(target) Release/obj.target/pdfutils/src/page.o
../src/page.cc: In constructor ‘Page::Page(Document*, int)’:
../src/page.cc:52: error: ‘poppler_page_get_label’ was not declared in this scope
make: *** [Release/obj.target/pdfutils/src/page.o] Error 1
make: Leaving directory `/home/adventhp/node_modules/pdfutils/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/adventhp/node_modules/pdfutils
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! pdfutils@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdfutils@0.3.2 install script.
npm ERR! This is most likely a problem with the pdfutils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdfutils
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdfutils"
npm ERR! cwd /home/adventhp
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/adventhp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Gottox** [comment]
Which version of poppler is installed? - I suspect it's to old for pdfutils.

**Comment by wmbutler** [comment]
Yeah, that seems to be the case. And unfortunately I can't find a yum
repository with a current version. Guess I'll switch to ubuntu for my
server.

On Thu, May 22, 2014 at 3:40 PM, Enno Boland notifications@github.comwrote:

> Which version of poppler is installed? - I suspect it's to old for
> pdfutils.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gottox/node-pdfutils/issues/10#issuecomment-43941232
> .

## 

Bill Butler
bill@butler.net
(615) 330-5044

**Comment by wmbutler** [comment]
OK, switched to ubuntu. Looking better, but I did get these warnings just and an FYI. Not sure if they are showstoppers yet because I haven't tested but it looks like there are some deprecated commands:

```
bbutler@PDF000:/home/adventhp$ sudo npm install pdfutils
sudo: unable to resolve host PDF000
npm WARN package.json adventhp@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/pdfutils
npm http 304 https://registry.npmjs.org/pdfutils
npm http GET https://registry.npmjs.org/pdfutils/-/pdfutils-0.3.2.tgz
npm http 200 https://registry.npmjs.org/pdfutils/-/pdfutils-0.3.2.tgz

> pdfutils@0.3.2 install /home/adventhp/node_modules/pdfutils
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
make: Entering directory `/home/adventhp/node_modules/pdfutils/build'
  CXX(target) Release/obj.target/pdfutils/src/document.o
  CXX(target) Release/obj.target/pdfutils/src/page.o
  CXX(target) Release/obj.target/pdfutils/src/page_job.o
  CXX(target) Release/obj.target/pdfutils/src/init.o
../src/init.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
../src/init.cc:9:2: warning: ‘void g_type_init()’ is deprecated (declared at /usr/include/glib-2.0/gobject/gtype.h:667) [-Wdeprecated-declarations]
  g_type_init();
  ^
../src/init.cc:9:14: warning: ‘void g_type_init()’ is deprecated (declared at /usr/include/glib-2.0/gobject/gtype.h:667) [-Wdeprecated-declarations]
  g_type_init();
              ^
  CXX(target) Release/obj.target/pdfutils/src/svg_size_hack.o
  CXX(target) Release/obj.target/pdfutils/src/link.o
  SOLINK_MODULE(target) Release/obj.target/pdfutils.node
  SOLINK_MODULE(target) Release/obj.target/pdfutils.node: Finished
  COPY Release/pdfutils.node
make: Leaving directory `/home/adventhp/node_modules/pdfutils/build'
pdfutils@0.3.2 node_modules/pdfutils
```

**Comment by Gottox** [comment]
The warnings aren't critical and can be ignored.
