### ISSUE TITLE
Error installing on Node v6.2.0

### ISSUE THREAD

**Issue by antoniobrandao** [Gottox/node-pdfutils#25]
npm install pdfutils --save

> pdfutils@0.3.2 install /Users/antoniobrandao/WEBROOT/Moobo/node_modules/pdfutils
> node-gyp rebuild

  CXX(target) Release/obj.target/pdfutils/src/document.o
In file included from ../src/document.cc:11:
In file included from ../src/document.h:7:
../src/page.h:10:27: error: expected class name
class Page : public node::ObjectWrap {
                          ^
../src/page.h:24:83: error: no type named 'AccessorInfo' in namespace 'v8'
                static v8::Handlev8::Value GetLinks(v8::Localv8::String property, const v8::AccessorInfo &info);
                                                                                            ~~~~^
../src/page.h:26:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handlev8::Value ConvertTo(const v8::Arguments& args);
                                                             ^~~~~~~~~~~~~
                                                             v8::internal::Arguments
/Users/antoniobrandao/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/document.cc:11:
In file included from ../src/document.h:8:
../src/page_job.h:18:30: error: expected class name
class PageJob : public node::ObjectWrap {
                             ^
../src/page_job.h:32:3: error: unknown type name 'uv_mutex_t'
                uv_mutex_t chunkMutex;
                ^
../src/page_job.h:34:3: error: unknown type name 'uv_async_t'
                uv_async_t message_finished;
                ^
../src/page_job.h:35:3: error: unknown type name 'uv_async_t'
                uv_async_t message_chunk;
                ^
../src/page_job.h:42:30: error: unknown type name 'uv_async_t'
                static void ChunkCompleted(uv_async_t\* handle, int status);
                                           ^
../src/page_job.h:43:28: error: unknown type name 'uv_async_t'
                static void JobCompleted(uv_async_t\* handle, int status);
                                         ^
../src/page_job.h:44:87: error: no type named 'AccessorInfo' in namespace 'v8'
                static v8::Handlev8::Value GetDimension(v8::Localv8::String property, const v8::AccessorInfo &info);
                                                                                                ~~~~^
In file included from ../src/document.cc:11:
../src/document.h:20:31: error: expected class name
class Document : public node::ObjectWrap {
                              ^
../src/document.h:31:3: error: unknown type name 'uv_mutex_t'
                uv_mutex_t jobMutex;
                ^
../src/document.h:33:3: error: unknown type name 'uv_mutex_t'
                uv_mutex_t stateMutex;
                ^
../src/document.h:35:3: error: unknown type name 'uv_work_t'
                uv_work_t worker;
                ^
../src/document.h:45:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handlev8::Value New(const v8::Arguments& args);
                                                       ^~~~~~~~~~~~~
                                                       v8::internal::Arguments
/Users/antoniobrandao/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/document.cc:11:
../src/document.h:48:82: error: no type named 'AccessorInfo' in namespace 'v8'
                static v8::Handlev8::Value GetPage(v8::Localv8::String property, const v8::AccessorInfo &info);
                                                                                           ~~~~^
../src/document.h:49:30: error: unknown type name 'uv_work_t'
                static void BackgroundLoad(uv_work_t\* req);
                                           ^
../src/document.h:50:32: error: unknown type name 'uv_work_t'
                static void BackgroundLoaded(uv_work_t\* req);
                                             ^
../src/document.h:52:22: error: unknown type name 'uv_work_t'
                static void Worker(uv_work_t _handle);
                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *_\* [Release/obj.target/pdfutils/src/document.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/antoniobrandao/WEBROOT/Moobo/node_modules/pdfutils
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdfutils" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! pdfutils@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdfutils@0.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pdfutils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdfutils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/antoniobrandao/WEBROOT/Moobo/npm-debug.log

**Comment by antoniobrandao** [comment]
😢
