### ISSUE TITLE
When attempting to install pdfutils

### ISSUE THREAD

**Issue by wmbutler** [Gottox/node-pdfutils#8]
```
[bbutler@PDF001 adventhp]$  npm install pdfutils
npm WARN package.json adventhp@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/pdfutils
npm http 304 https://registry.npmjs.org/pdfutils

> pdfutils@0.3.1 install /home/adventhp/node_modules/pdfutils
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/adventhp/node_modules/pdfutils
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! pdfutils@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdfutils@0.3.1 install script.
npm ERR! This is most likely a problem with the pdfutils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdfutils
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdfutils"
npm ERR! cwd /home/adventhp
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/adventhp/npm-debug.log
npm ERR! not ok code 0

```

**Comment by wmbutler** [comment]
Any help would be greatly appreciated.

**Comment by Gottox** [comment]
Did you try [this](https://github.com/TooTallNate/node-gyp/issues/363#issuecomment-33212812)?

Also removing gyp from the system helped people: `sudo apt-get remove gyp`

**Comment by wmbutler** [comment]
My particular problem seems to be related to poppler-glib-devel and isue
with installing current versions with yum since I can't find any
repositories with current versions of poppler.

If you run across any, I'd love to hear about it.

On Thu, May 22, 2014 at 2:39 AM, Enno Boland notifications@github.comwrote:

> Did you try thishttps://github.com/TooTallNate/node-gyp/issues/363#issuecomment-33212812
> ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gottox/node-pdfutils/issues/8#issuecomment-43857251
> .

## 

Bill Butler
bill@butler.net
(615) 330-5044

**Comment by wmbutler** [comment]
Abandoned attempting to use CentOS and switched to Ubuntu. Recommend reverting my readme.md pull request.
